### ISSUE TITLE
php artisan schematics:install failed

### ISSUE THREAD

**Issue by saimyosett** [mtolhuys/laravel-schematics#21] opened 2020-03-09 03:34 UTC
**LogicException**

at vendor/laravel/framework/src/Illuminate/Routing/Route.php:1039
    1035|      */
    1036|     public function prepareForSerialization()
    1037|     {
    1038|         if ($this->action['uses'] instanceof Closure) {
  > 1039|             throw new LogicException("Unable to prepare route [{$this->uri}] for serialization. Uses Closure.");
    1040|         }
    1041|
    1042|         $this->compileRoute();
    1043|

      +32 vendor frames
  33  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by brocorp-dev** [comment] 2020-03-09 04:26
Hi guys, 

Same behavior on a fresh Laravel 7.0.8 install. 

If you remove all your route content (in api.php and web.php), install can run but you got this error when you visit {your-app}/schematics:

`InvalidArgumentException
HTTP 500 Internal Server Error
Action Facade\Ignition\Http\Controllers\ExecuteSolutionController not defined.`

**Comment by mtolhuys** [comment] 2020-03-09 15:22
Hi @saimyosett ,

This is due to Laravel being unable to cache routes that contains closures. Duplicate of https://github.com/mtolhuys/laravel-schematics/issues/11

@brocorp-dev I've just tested out in a fresh 7.0.8 myself. Didn't got any issues. By  the looks of the Exception message you are getting it seems to be related to your `facade\ignition` setup though.

**Comment by ejntaylor** [comment] 2020-03-09 16:22
Hi @mtolhuys I have this issue too, left a comment over here as marked as duplicate:

https://github.com/mtolhuys/laravel-schematics/issues/11#issuecomment-596622251

Not sure if that is best practice as it's a closed ticket, so leaving a note here if thats ok. Looking forward to trying Schematics out. Thanks

**Comment by Chouchen** [comment] 2020-03-09 17:24
I had the same bug, commented `Artisan::call('route:cache');` in `Install.php`, relaunched `php artisan schematics:install` and it worked well.

I suggest something like this : 

```
try {
    Artisan::call('route:cache');
} catch (\LogicException $e) {
     $this->warn('Routes couldn\'t be cached because of Closure.');
}
```

**Comment by mtolhuys** [comment] 2020-03-09 17:26
Hi @raisonon & @Chouchen, I like the try / catch approach, including it now since this issue is coming up too much. 

Like this:

![Screenshot from 2020-03-09 18-28-51](https://user-images.githubusercontent.com/10849136/76240664-e733b080-6233-11ea-8aa0-caf992efbfa4.png)

**Comment by mtolhuys** [comment] 2020-03-09 17:52
Done! 0.9.11 contains this.

**Closed as completed by mtolhuys** 2020-03-09 17:52 UTC
Labels: duplicate

**Comment by ejntaylor** [comment] 2020-03-09 18:26
Fab - so on a new install just head to web.php and api.php and remove the routes auto included (that use closures). Thanks!
