### ISSUE TITLE
Problems with the relationships

### ISSUE THREAD

**Issue by paolaDC** [mtolhuys/laravel-schematics#19] opened 2020-03-08 07:55 UTC
Good morning!!!

I'm sorry, but my english is not good.

When I create a relationship between two models and schematics it implements it in the code of the corresponding model, it does it between the namespace declaration zone and the class, it does not add it to the end of the class, as would be correct. That must be defined somewhere or is it a bug? 
![user_model](https://user-images.githubusercontent.com/55342246/76158916-3cc86a00-611b-11ea-9aae-a3a23cb679bb.png)

And then, I have a problem with the migrations...

Please, anyone helps me?

**Comment by mtolhuys** [comment] 2020-03-08 13:48
Hi @paolaDC !

This could be a bug. Could you perhaps share the whole User class so I can test it out here?

The package looks for the last closing `}` of the file assuming its the end of the class. In your case this doesn't seem to work. 

If it's a bug I'll try to fix it asap.

**Comment by mtolhuys** [comment] 2020-03-08 14:23
Also curious about the migration issue you are having by the way. Could you explain that one in a different issue so we can keep them separated?

**Comment by elbojoloco** [comment] 2020-03-09 19:25
I'm experiencing the same issue, but even worse.
![image](https://user-images.githubusercontent.com/7912315/76249555-e0ad3500-6243-11ea-8f22-0ac794770c92.png)
This is what my User model looks like after adding a Tournament model and a hasMany relation between them. It seems the `<?php` tag has been replaced with the relationship method.

Also, when undoing this change and refreshing the schematics page, the User model is no longer visible. 

Edit: after clearing application cache the User model becomes visible again.

**Comment by mtolhuys** [comment] 2020-03-09 19:41
Hi @elbojoloco ,

Ouch, that looks really nasty. Can you send the whole class? I'm having trouble reproducing this issue. I'm also curious about the laravel version and php version you're on.

**Comment by elbojoloco** [comment] 2020-03-09 21:04
@mtolhuys 
PHP 7.2.19
Laravel 7.0.8
Windows 10 running Laragon with nginx as local development environment

**Comment by mtolhuys** [comment] 2020-03-09 21:29
Thanks @elbojoloco, I'm setting up my windows environment. Has been a while ago that it got tested on windows and it seems confirmed it is a windows related issue. Hope to fix it asap.

**Comment by elbojoloco** [comment] 2020-03-09 21:48
@mtolhuys It is in fact to do with the PHP_EOL const being different for the OS's, I've found a regex that seems to work locally:

`$lines = preg_split('/\r\n|\r|\n/', file_get_contents($file));`

If you hadn't found this problem by now, I could create a PR :)

**Comment by mtolhuys** [comment] 2020-03-09 22:05
Really nice find @elbojoloco! I noticed it too and released it with 0.9.12. Feel free with anything to create a PR though, I'm really looking forward to those! :)

**Comment by elbojoloco** [comment] 2020-03-09 22:06
I created a PR just as you posted this comment haha, i closed it. Thanks for the swift fix, can not wait to play with this package some more!

**Comment by mtolhuys** [comment] 2020-03-09 22:08
Haha I'm glad and impressed you got to it this fast (not knowing the code-base).

**Comment by paolaDC** [comment] 2020-03-10 05:46
In my case , my enviromment is PHP 7.2.19
Laravel 6
Windows 10

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by mtolhuys** [comment] 2020-03-10 06:05
@paolaDC you can update to 0.9.12. It should fix the problem with generating relations.

**Comment by paolaDC** [comment] 2020-03-10 06:12
Thank you very much!!!!!

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Closed as completed** 2020-03-10 07:39 UTC
Labels: bug, question
