### ISSUE TITLE
issue with adding relationships

### ISSUE THREAD

**Issue by mobayen** [mtolhuys/laravel-schematics#25] opened 2020-03-09 19:48 UTC
I created "User hasMany Posts" relationship 
this is what the User.php file look like after that:

```
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts()
    {
        return $this->hasMany(\App\Models\Post::class);
    }
}

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

**Comment by mtolhuys** [comment] 2020-03-09 20:05
Hi @mobayen ,

Strange, I can't seem to reproduce this with your User class. Can you tell me what environment your working with? I'm especially curious about laravel version, php version and the OS. Are you perhaps on Windows?

P.S: Duplicate of https://github.com/mtolhuys/laravel-schematics/issues/19

**Comment by mobayen** [comment] 2020-03-09 20:15
Hi @mtolhuys 

Yes, it is strange! because it is not something you miss!!

yup, it is a Windows.
PHP: v7.2.16
Laravel: v7.0.8
OS: windows 10 pro

**Comment by mtolhuys** [comment] 2020-03-09 20:17
Thanks for the info @mobayen !

This will greatly help the investigation. Hope to fix this soon.

**Comment by mtolhuys** [comment] 2020-03-09 22:03
@mobayen could you update to 0.9.12 and try again? It should be fixed now.

**Comment by elbojoloco** [comment] 2020-03-09 22:14
Tested on 0.9.12 and works for me on windows.

**Closed as completed** 2020-03-10 07:39 UTC
Labels: bug, duplicate, question

**Comment by mobayen** [comment] 2020-03-10 14:25
cool,
yup it is working for me as well
